name: Build&Push DockerImage for Spring_jdk17_maven

on:
  workflow_dispatch:
    inputs:
      workFolder:
        description: 'Working Folder'
        required: true
        default: 'Spring_jdk17_maven'  # preset path 
      dockerTag:
        description: 'Docker Image Tag'
        required: false
        default: 'renchi/java_pipeline:latest'
      platforms:
        description: 'Build Platforms'
        required: false
        default: 'linux/amd64,linux/arm64'
  # push:
    # branches: [ main ]  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.workFolder }}
        file: ./${{ github.event.inputs.workFolder }}/Dockerfile
        push: true
        tags: ${{ github.event.inputs.dockerTag }}
        platforms: ${{ github.event.inputs.platforms }}

